spring:
  application:
    name: mq-test-utils-test

mq:
  test:
    connection:
      host: localhost
      port: 1414
      queue-manager: QM1
      channel: DEV.ADMIN.SVRCONN
      user: admin
      password: passw0rd
      client-id: MQ_TEST_CLIENT_TEST
    queues:
      request: DEV.QUEUE.1
      response: DEV.QUEUE.2
      dead-letter: DEV.DEAD.LETTER.QUEUE
      test-queue: TEST.QUEUE.JUNIT
    timeout:
      receive: 3000
      send: 2000
    retry:
      max-attempts: 2
      delay: 500

logging:
  level:
    com.example.mq: DEBUG
    com.ibm.mq: WARN
    org.springframework: WARN
    root: INFO