spring:
  application:
    name: mq-test-utils-tandem

# Tandem Environment MQ Configuration
mq:
  test:
    connection:
      # Tandem MQ Server Configuration - UPDATE THESE VALUES
      host: ${MQ_HOST:tandem-mq-server.company.com}
      port: ${MQ_PORT:1414}
      queue-manager: ${MQ_QUEUE_MANAGER:PROD_QM1}
      channel: ${MQ_CHANNEL:SYSTEM.DEF.SVRCONN}
      user: ${MQ_USER:mquser}
      password: ${MQ_PASSWORD:mqpass}
      client-id: ${MQ_CLIENT_ID:TANDEM_TEST_CLIENT}
    queues:
      # Production Queue Names - UPDATE THESE VALUES
      request: ${MQ_REQUEST_QUEUE:PROD.REQUEST.QUEUE}
      response: ${MQ_RESPONSE_QUEUE:PROD.RESPONSE.QUEUE}
      dead-letter: ${MQ_DLQ:PROD.DEAD.LETTER.QUEUE}
      test-queue: ${MQ_TEST_QUEUE:PROD.TEST.QUEUE}
    timeout:
      receive: ${MQ_RECEIVE_TIMEOUT:10000}
      send: ${MQ_SEND_TIMEOUT:5000}
    retry:
      max-attempts: ${MQ_RETRY_ATTEMPTS:5}
      delay: ${MQ_RETRY_DELAY:2000}

# Production Logging
logging:
  level:
    com.example.mq: INFO
    com.ibm.mq: WARN
    org.springframework: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /tmp/mq-test-utils.log
    max-size: 10MB
    max-history: 5