spring:
  application:
    name: mq-test-utils

mq:
  test:
    connection:
      host: localhost
      port: 1414
      queue-manager: QM1
      channel: DEV.ADMIN.SVRCONN
      user: admin
      password: passw0rd
      client-id: MQ_TEST_CLIENT
    queues:
      request: DEV.QUEUE.1
      response: DEV.QUEUE.2
      dead-letter: DEV.DEAD.LETTER.QUEUE
      test-queue: TEST.QUEUE
    timeout:
      receive: 5000
      send: 3000
    retry:
      max-attempts: 3
      delay: 1000

logging:
  level:
    com.example.mq: DEBUG
    com.ibm.mq: INFO